start node microservice-category/server.js
start node microservice-product/server.js
start node microservice-order/server.js
start node microservice-saga-category/server.js
start node microservice-saga-product/server.js
start node microservice-account/server.js
start node microservice-scenario/server.js
start node microservice-budget/server.js
start node microservice-saga-account/server.js
start node web-host/server.js