start node microservice-category/server.js
start node microservice-saga-category/server.js
start node microservice-account/server.js
start node microservice-scenario/server.js
start node microservice-budget/server.js
start node microservice-saga-account/server.js
start node microservice-forecast/server.js
start node microservice-saga-budget/server.js
start node microservice-actual/server.js
start node web-host/server.js